### ISSUE TITLE
cant connect to database

### ISSUE THREAD

**Issue by krappleby** [easyphp/WEBSERVER#13]
HI, 

Im having problems connecting with mysql using your phpserver, code im using is as follows

```
<?php
$servername = "localhost";
$username = "root";
$password = "******";
$dbname = "sales";
 
// Create connection
$conn = mysql_connect($servername, $username, $password, $dbname);
 
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 
echo "Connected successfully";
?>
```

what is the problem this is not connecting, ic annot run any queryies on this connetion.. 
pdo doesnt worlk ans mysqli doesnt appera to work either.. 

please help

**Comment by CyrilCharlier** [comment]
Hi, 

For Easyphp, root is with a "blank" password.

Cyril
