### ISSUE TITLE
Multi IP addresses problem

### ISSUE THREAD

**Issue by pavelseb** [easyphp/WEBSERVER#19]
I have several ethernet cards (physical and virtuals) and in my case the dashboard read and use the IP address of one from virtual card. This is problem because this IP is not available for other machines on LAN.

Even I modify httpd.conf the dashboard change my added IP to wrong IP.

I think the problem s here:
if ($http_ip != $network_ip AND $http_ip != "0.0.0.0") {
	$httpdconf = str_replace ($http_ip, $network_ip, $httpdconf);
	file_put_contents('..\binaries\httpserver\conf\httpd.conf', $httpdconf);
	$alert_ipmismatch = 1;
}

because the dashboard overwrite the ip from conf file with the ip acquired from "getHostByName".
But I think the configuration file should have max priority, because in such case is ip settings doesn't matter. And this is little bit confusing.

Or dashboard could provide to user to change the IP directly.

**Comment by easyphp** [comment]
Now on the TODO list.
