### ISSUE TITLE
Getting Invalid Request Error. Need Help!!!

### ISSUE THREAD

**Issue by Mitsaras1911** [easyphp/WEBSERVER#2]

**Comment by Mitsaras1911** [comment]
![image](https://cloud.githubusercontent.com/assets/8915915/12148564/c9e93c2c-b4a7-11e5-8f86-9d87a7865441.png)

**Comment by easyphp** [comment]
Hi
Can you give us more information ?
Configuration, logs, version...
Regards

**Comment by edmendel** [comment]
We simple installed EasyPHP 14.1b and we are receiving the same error above.
When I try to reach Dashboard I receive the "invalid request" in browser.

What we are making wrong?

Have you some  idea?
