### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by AnonymeUSB** [easyphp/WEBSERVER#26]
Je n'arrive a aller sur le tableau de bord car ça marque : 
Ce site est inaccessible127.0.0.1 n'autorise pas la connexion.
Voici quelques conseils :

Vérifier la connexion
Vérifier le proxy et le pare-feu
ERR_CONNECTION_REFUSED

**Comment by easyphp** [comment]
Y a-t-il une autre version de PHP qui est en trina de tourner ? PHP est-il déjà dans le PATH ?
Ouvrir Task Manager et tuer tous les proces qui peuvent parasiter le serveur, puis reessayer.
