### ISSUE TITLE
Can't listen to port other than 80, 8000, 8888, 8008

### ISSUE THREAD

**Issue by mathieuprog** [easyphp/WEBSERVER#5]
In the backend interface for 16.1, I can't choose a port other than 80, 8000, 8888 or 8008.
Why impose such a restriction ?

Use case for custom port: I'm used to launch multiple web servers listening to port 80 + the php version
e.g. 8056 for web server with php 5.6.x
8070 for web server with php 7.0.x
etcetera

Tried to change the Apache configuration but the port gets overriden by the value I have to choose in the interface.

**Comment by Noctuabundus** [comment]
I had the same problem. After some digging i found out that you can update/change preconfigured ports at EasyPHP\eds-binaries\httpserver\apache\eds-app-dashboard.php

**Comment by easyphp** [comment]
Open 'eds-app-actions.php' and add numbers.
