### ISSUE TITLE
Dashboard not loading

### ISSUE THREAD

**Issue by ghost** [easyphp/WEBSERVER#6]
Hi,

I am working on an OS and we are building a website. We are using your server. The dashboard loaded when we got the software but now it just loads for ages. This is alright on our computers as we can find the ip from the port manager but we cant add modules or anything like that because the dashboard won't load. Also we cant get the public IP as a link to the site.

Thanks,

The JumpOS Team

**Comment by rudyxxx** [comment]
I have the same issue, i tried to reinstall completely Web Server and for some days worked fine. After a bit and without apparent reasons stopped access and loading forever.

I can't open:

- http://localhost
- 127.0.0.1:10000

Nothing worked for me. Today the server is in production enviroment and i need a solution.

Easyphp team can contact me.
![image](https://cloud.githubusercontent.com/assets/24913824/21640248/e55ed98a-d274-11e6-87f3-33143d295a3f.png)

**Comment by kechacha** [comment]
Hi All

Since 5 days I'm having issue. Dashboard is not able to start.
Anyone help please !
