### ISSUE TITLE
How do I manually update php binaries in EasyPHP Web Server?

### ISSUE THREAD

**Issue by GazbonicAcid** [easyphp/WEBSERVER#9]
How do I manually update the version of php my EasyPHP Web Server installation uses **_WITHOUT_** using the EasyPHP Warehouse?
I spent all of my expendable income for the month on a new computer and don't have the $10 to "rent a key" to the EasyPHP module warehouse.
Also asked on [StackOverflow](http://stackoverflow.com/questions/40387137/how-do-i-manually-update-php-binaries-in-easyphp-web-server)

**Comment by mastacheata** [comment]
Grab a PHP version for the Apache Build you use in your DevServer. (I'm using 32bit version, so VC11 x86 builds are what I'd need)
Put that in a new directory inside the eds-binaries/php/ subdir of your Devserver. (No idea if you have to match the naming scheme of EasyPHP, but it won't hurt)
Configure PHP to your needs (adjust php.ini and install extensions as you need/want them).
Copy the eds-app-* files (3x php 1x exe) from your stock php tp your custom php folder.
Adjust eds-app-settings.php to match the right filenames and the proper version/build info.

That's all the warehouse modules do as well. The Dashboard thing (which is a seperate webserver) will pick up your version and you can select it from the menu.

You can leave out the last two steps and instead configure apache by hand to use your PHP module or run PHP as CGI/FastCGI, but if you do that you can just as well throw EasyPHP away completely and just set up A,M&P yourself from scratch.

**Comment by mikerockett** [comment]
@mastacheata - I've done this for a few PHP releases for dev-server, and a few versions would not start. More than likely: it was a problem with the releases themselves, and not with dev-server.
